name: bbqrdart
description: Simple and easy to use bbqr implementation in dart
version: 1.0.0
repository: https://github.com/mrcyjanek/bbqrdart

environment:
  sdk: ^3.6.2

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
